name: Create Branch Protection

on: 
  push:
    branches:
      - "feature/setup-branch-protection"

jobs:
  job-id:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Strategy to lock branches
        uses: Hatzelencio/branch-protection@v1.0.0
        with:
          path: .github/config/branch-protection.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}